'use client';
import {useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
type Candidate={id:number;name:string;score:number;strengths:string[];gaps:string[];skill_relevance:number;experience_alignment:number;qualification_match:number;refinement_trace:{pass:number;score:number}[]};
export default function Home(){
 const [job,setJob]=useState<number|null>(null),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[files,setFiles]=useState<FileList|null>(null),[list,setList]=useState<Candidate[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function run(){try{setBusy(true);setError(''); const jd=new FormData();jd.append('title',title);jd.append('description',description);let r=await fetch(`${API}/jobs`,{method:'POST',body:jd});if(!r.ok)throw Error(await r.text());const j=await r.json();setJob(j.id);if(files?.length){let f=new FormData();Array.from(files).forEach(x=>f.append('files',x));r=await fetch(`${API}/jobs/${j.id}/resumes`,{method:'POST',body:f});if(!r.ok)throw Error(await r.text());}r=await fetch(`${API}/jobs/${j.id}/shortlist`);const out=await r.json();setList(out.candidates)}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}}
 return <main><header><span className="eyebrow">CPU-FIRST RECRUITING INTELLIGENCE</span><h1>SmartHire <i>AI</i></h1><p>Evidence-led screening with recursive refinement — not opaque automation.</p></header><section className="panel"><h2>Create a shortlist</h2><label>Role title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Senior Backend Engineer"/></label><label>Job description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Paste requirements, skills, and experience…"/></label><label>Resumes <small>PDF, DOCX, or TXT · choose several</small><input type="file" multiple accept=".pdf,.docx,.txt" onChange={e=>setFiles(e.target.files)}/></label><button disabled={busy||!title||!description} onClick={run}>{busy?'Screening…':'Build ranked shortlist'}</button>{error&&<p className="error">{error}</p>}</section>{job&&<section><div className="resultHead"><h2>Ranked candidates</h2><span>Job #{job} · recruiter review required</span></div>{list.length===0?<p className="empty">Upload resumes to see the shortlist.</p>:list.map((c,i)=><article className="candidate" key={c.id}><div className="rank">{i+1}</div><div className="candidateTitle"><h3>{c.name}</h3><span>Recursive match score</span></div><strong className="score">{c.score}%</strong><div className="metrics"><Metric n="Skills" v={c.skill_relevance}/><Metric n="Experience" v={c.experience_alignment}/><Metric n="Qualifications" v={c.qualification_match}/></div><div className="evidence"><p><b>Strengths</b>{c.strengths.map(x=><span className="good" key={x}>{x}</span>)}</p><p><b>Gaps</b>{c.gaps.length?c.gaps.map(x=><span className="gap" key={x}>{x}</span>):<span>None detected from stated requirements</span>}</p></div><details><summary>View {c.refinement_trace.length}-pass reasoning trace</summary>{c.refinement_trace.map(t=><span className="trace" key={t.pass}>Pass {t.pass}: {t.score}%</span>)}</details></article>)}</section>}</main>}
function Metric({n,v}:{n:string;v:number}){return <div><span>{n}</span><b>{v}%</b><i><em style={{width:`${v}%`}}/></i></div>}
