'use client';
import {useState} from 'react';
import './upload.css';
const API=process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
type Breakdown={label:string;weight:number;points:number;detail:string};
type Review={evidence_found:string[];resume_edits:string[];growth_plan:string[];research_topics:string[]};
type Details={score_interpretation:string[];resume_blueprint:string[];interview_preparation:string[];mentor_narrative:string;evidence_limitations:string};
type Candidate={id:number;name:string;score:number;strengths:string[];gaps:string[];skill_relevance:number;experience_alignment:number;qualification_match:number;recommendation:string;score_context:string;score_breakdown:Breakdown[];deep_resume_review:Review;detailed_explanation:Details;refinement_trace:{pass:number;score:number}[]};
const emptyReview={evidence_found:[],resume_edits:[],growth_plan:[],research_topics:[]};
const SearchLink=({topic}:{topic:string})=><a className="researchLink" target="_blank" rel="noreferrer" href={`https://www.google.com/search?q=${encodeURIComponent(`${topic} official documentation tutorial`)}`}>Learn {topic} ↗</a>;
export default function Home(){
 const [job,setJob]=useState<number|null>(null),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[files,setFiles]=useState<FileList|null>(null),[list,setList]=useState<Candidate[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function run(){try{setBusy(true);setError('');const jd=new FormData();jd.append('title',title);jd.append('description',description);let r=await fetch(`${API}/jobs`,{method:'POST',body:jd});if(!r.ok)throw Error(await r.text());const j=await r.json();setJob(j.id);if(files?.length){const f=new FormData();Array.from(files).forEach(x=>f.append('files',x));r=await fetch(`${API}/jobs/${j.id}/resumes`,{method:'POST',body:f});if(!r.ok)throw Error(await r.text())}r=await fetch(`${API}/jobs/${j.id}/shortlist`);if(!r.ok)throw Error(await r.text());setList((await r.json()).candidates)}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}}
 return <main><header><span className="eyebrow">CPU-FIRST RECRUITING INTELLIGENCE</span><h1>SmartHire <i>AI</i></h1><p>Evidence-led screening with recursive refinement — not opaque automation.</p></header><section className="panel"><h2>Create a shortlist</h2><label>Role title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Senior Backend Engineer"/></label><label>Job description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Paste requirements, skills, and experience…"/></label><label>Resumes <small>PDF, DOCX, or TXT · choose several</small><input className="uploadInput" type="file" multiple accept=".pdf,.docx,.txt" onChange={e=>setFiles(e.target.files)}/></label><button disabled={busy||!title||!description} onClick={run}>{busy?'Screening…':'Build ranked shortlist'}</button>{error&&<p className="error">{error}</p>}</section>{job&&<section><div className="resultHead"><h2>Ranked candidates</h2><span>Job #{job} · recruiter review required</span></div>{list.length===0?<p className="empty">Upload resumes to see the shortlist.</p>:list.map((c,i)=><CandidateCard key={c.id} c={c} i={i}/>)}</section>}</main>}
function CandidateCard({c,i}:{c:Candidate;i:number}){const review=c.deep_resume_review||emptyReview;const details=c.detailed_explanation;return <article className="candidate"><div className="rank">{i+1}</div><div className="candidateTitle"><h3>{c.name}</h3><span>{c.recommendation||'Recruiter review required'}</span></div><strong className="score">{c.score}%</strong><div className="metrics"><Metric n="Skills" v={c.skill_relevance}/><Metric n="Experience" v={c.experience_alignment}/><Metric n="Qualifications" v={c.qualification_match}/></div><div className="evidence"><p><b>Strengths</b>{c.strengths.map(x=><span className="good" key={x}>{x}</span>)}</p><p><b>Gaps</b>{c.gaps.length?c.gaps.map(x=><span className="gap" key={x}>{x}</span>):<span>None detected from stated requirements</span>}</p></div><section className="mentor"><h4>Mentor score review</h4><p>{c.score_context}</p><div className="breakdown">{(c.score_breakdown||[]).map(x=><div className="breakdownRow" key={x.label}><div><b>{x.label} <small>({x.weight}% weight)</small></b><span>{x.detail}</span></div><strong>{x.points} / {x.weight} pts</strong></div>)}</div><Coach title="Evidence found" items={review.evidence_found}/><Coach title="Make the resume stronger" items={review.resume_edits}/><Coach title="Build real capability" items={review.growth_plan}/>{review.research_topics.length>0&&<div className="research"><h4>Research role skills</h4><p>These searches are opened by you and use job skills only—not candidate personal data.</p>{review.research_topics.map(x=><SearchLink key={x} topic={x}/>)}</div>}<Detailed details={details}/></section><details><summary>View {c.refinement_trace.length}-pass reasoning trace</summary>{c.refinement_trace.map(t=><span className="trace" key={t.pass}>Pass {t.pass}: {t.score}%</span>)}</details></article>}
function Coach({title,items}:{title:string;items:string[]}){return items.length?<div className="coach"><h4>{title}</h4><ul>{items.map(x=><li key={x}>{x}</li>)}</ul></div>:null}
function Detailed({details}:{details:Details|undefined}){return details?<details className="detailReport"><summary>Read the full mentor explanation</summary><p className="mentorVoice">{details.mentor_narrative}</p><Coach title="What this score means" items={details.score_interpretation}/><Coach title="Resume blueprint" items={details.resume_blueprint}/><Coach title="Interview preparation" items={details.interview_preparation}/><p>{details.evidence_limitations}</p></details>:null}
function Metric({n,v}:{n:string;v:number}){return <div><span>{n}</span><b>{v}%</b><i><em style={{width:`${v}%`}}/></i></div>}
